Minor fixes across CSV data handling classes for compatibility
CalicoChloe/Thrifty-K9 pull request #8
Opened 2023-09-27 17:15 UTC by ConnorDMurdock

Renamed FileReaderCSV.kt to CSVParser.kt for a more accurate name. Minor changes to CSVReader.kt and CSVParser.kt to be more compatible. Replaced testdata.csv with the updated version.

2023-09-27 17:30 UTC, jellis2-GGC approved these changes
Nice job!

2023-09-27 17:32 UTC, AbdoulieJNJie98 approved these changes

2023-09-27 17:59 UTC, CalicoChloe requested changes

2023-09-27 17:59 UTC, CalicoChloe commented on app/src/main/java/com/example/pricingpal/model/CSVReader.kt
>   *  called in MainActivity.kt using the keyword "this" as the context
This comment block needs to be changed to reflect the change to an object.  The "this" keyword is no longer used.

2023-09-27 18:07 UTC, CalicoChloe approved these changes

2023-09-28 22:01 UTC, Shianne1 approved these changes

2023-09-28 22:22 UTC, byeboah9 approved these changes

2023-09-28 22:28 UTC, merged